services:
  - type: web
    name: flask-mediapipe-service
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    build:
      pythonVersion: 3.10.12